name: foodiee
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


# ---------------------Packages-----------------------------
dependencies:
  flutter:
    sdk: flutter

  #  Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2

  #  Icons packages
  cupertino_icons: ^1.0.2

  #  State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0

#  Product Specific Packages


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  #  ------------------Local Assest ------------------
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

